version: '3.9'

services:
  node-red:
    image: nodered/node-red:3.0.2
    restart: always
    environment:
      TZ: '${TIMEZONE}'
    volumes:
      - './Data:/data'
    networks:
      - traefik-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.tls=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.entrypoints=https'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.rule=Host(`${NODERED_FQDN}`)'
      #- 'traefik.http.routers.${PROJECT_IDENTIFIER}.middlewares=middlewares-authentik@file'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.service=${PROJECT_IDENTIFIER}'
      - 'traefik.http.services.${PROJECT_IDENTIFIER}.loadbalancer.server.port=1880'

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    external: true
